[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = "0.7.6"    # Override for the solc version (setting this ignores `auto_detect_solc`)

remappings = [
    'ds-test/=lib/tinlake-math/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'tinlake-auth/=lib/tinlake-title/lib/tinlake-auth/src/',
    'tinlake-erc20/=lib/tinlake/lib/tinlake-erc20/src/',
    'tinlake-math/=lib/tinlake-math/src/',
    'tinlake-title/=lib/tinlake-title/src/',
    'tinlake/=lib/tinlake/src/'
]