[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'tinlake-auth/=lib/tinlake-rpc-tests/lib/tinlake-title/lib/tinlake-auth/src/',
    'tinlake-math/=lib/tinlake-rpc-tests/lib/tinlake-math/src/',
    'tinlake-rpc-tests/=lib/tinlake-rpc-tests/',
    'tinlake-title/=lib/tinlake-rpc-tests/lib/tinlake-title/src/',
    'forge-std/=lib/forge-std/src/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config